// src/components/ui/pad.tsx
import React from 'react';

interface PadProps {
  active: boolean;
  onClick: () => void;
  size?: 'sm' | 'md' | 'lg';
  className?: string;
}

export const Pad: React.FC<PadProps> = ({
  active,
  onClick,
  size = 'md',
  className = '',
}) => {
  const padSize = {
    sm: 'w-8 h-8',
    md: 'w-12 h-12',
    lg: 'w-16 h-16',
  }[size];

  return (
    <div
      className={`${padSize} ${className} rounded-md relative cursor-pointer transition-all duration-200 ${active ? 'bg-purple-900/50' : 'bg-zinc-800'}`}
      onClick={onClick}
    >
      <div className={`absolute inset-0 rounded-md ${active ? 'bg-purple-500/20' : 'bg-transparent'} shadow-lg border border-zinc-700`}>
        <div className={`absolute inset-0 flex items-center justify-center ${active ? 'opacity-100' : 'opacity-0'} transition-opacity duration-200`}>
          <div className={`w-3 h-3 rounded-full ${active ? 'bg-purple-400' : 'bg-transparent'} shadow-lg shadow-purple-500/50`} />
        </div>
      </div>
    </div>
  );
};

export default Pad;

// web/src/lib/components/Pad.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
const dispatch = createEventDispatcher();

  export let label: string = '';
  export let trackColor: string = 'text-blue-500';
  export let active: boolean = false;
  export let selected: boolean = false;
  
  function handleClick() {
    dispatch('padclick');
  }
</script>

<button
  on:click={handleClick}
  class="aspect-square w-full bg-rytm-surface/80 relative border rounded-md shadow-md transition-all focus:outline-none overflow-hidden active:scale-[0.97]"
  class:border-rytm-accent={selected}
  class:border-rytm-border={!selected}
  >
  <!-- Active state glow/indicator -->
  {#if active}
    <div class="absolute inset-0 bg-gradient-to-br from-white/10 to-transparent opacity-70"></div>
  <div class="absolute top-1.5 right-1.5 w-2 h-2 rounded-full bg-green-400 shadow-glow-sm shadow-green-400/70"></div>
  {/if}
  
  <!-- Selected state indicator -->
  {#if selected}
    <div class="absolute inset-0 border-2 border-rytm-accent rounded-md pointer-events-none"></div>
  {/if}
  
  <!-- Label in center -->
  <div class="absolute inset-0 flex items-center justify-center">
    <span class="{trackColor} font-bold text-lg">{label}</span>
  </div>
  
  <!-- Bottom gradient for depth -->
  <div class="absolute inset-x-0 bottom-0 h-1/4 bg-gradient-to-t from-black/20 to-transparent"></div>
</button>

<style>
  .shadow-glow-sm {
    box-shadow: 0 0 8px var(--tw-shadow-color);
  }
</style>
